### ISSUE TITLE
Obtain a reference to a python instantiation of the underlying solver

### ISSUE THREAD

**Issue by marcovc** [MiniZinc/minizinc-python#103]
Hi,

I am a big minizinc fan, and so would first like to thank you for creating these python bindings to this amazing tool.

I guess the one thing left that is still holding me back from adopting minizinc as default modeling language, is the ability to get a low-level interface to the underlying solver. What I mean is to be able to do something like this:

```python
model = Model("model.mzn")
gurobi = Solver.lookup("gurobi")
instance = Instance(gurobi, model)
guroby_py_model = instance.get_underlying_solver(gurobi) # < ----- this
```

The reason for this, is that then I am not locked in the current subset of functionality provided by minizinc for solving optimization problems. In the example, gurobi_py_model would have all the functionality available in gurobi official python version, which includes features like dynamically adding cuts, warm starts, heuristics, etc.

An integration like this seems to bring the best of both worlds: use minizinc for modelling which is where it excels, and then use solver library for fine tuning the solving process.

For the particular case of gurobi or other MIP solvers, it seems this would not be hard to accomplish: we would just need to add all constraints into a gurobipy.Model and return it. Or am I missing something?

I suppose that this is not something we could do for every solver because not every solver has a python interface. 

Is this something you would consider adding to this library?

Thanks!
Marco

**Comment by Dekker1** [comment]
Hi Marco,

I'm afraid this is not something that the MiniZinc Python interface could provide.

It is certainly possible to start with a solver independent model in MiniZinc, and then once you discover what method works best make it specific to your solver using solver specific functions and options.

However, MiniZinc has its own interfaces to the underlying solvers. It connects directly to Gurobi, rather than using the Gurobi Python interface. This means that it would require an entirely independent compiler backend to compile the MiniZinc model to the Gurobi modelling layer (and another backend for the next solver). Although this might interesting, this is not a goal for the MiniZinc project.

Instead we would rather provide the options that you need to fine-tune your solving performance.

**Comment by marcovc** [comment]
Oh, that's a shame. Thanks!
