### ISSUE TITLE
Support np.array as instance parameter

### ISSUE THREAD

**Issue by artsiomkaltovich** [MiniZinc/minizinc-python#15]
Currently np.array are not supported as parameter of the model and generates ``TypeError: Object of type 'ndarray' is not JSON serializable``. But numpy is very popular and widely used library for working with arrays.

I think minizinc-python should support it, I would like to add this support, but before I want to ask what is the best way to do it:

1. Convert np.array to list of list of ... and return string representation of such list. But it will take some time to convert numpy array in such form, and slow down the model execution.
2. Flatten the array and return string [a1, a2, ..., an]. But I am not sure all version of MiniZinc will automatically convert such array into correct form (if the array is 2d or more d). Does it?
3. Just pass str(np.array) and add support of the array in such form to minizinc itself.

What is the best choise?

Regards,
Artyom.

**Comment by Dekker1** [comment]
Thank you for the feedback and I'm happy to hear that you are willing to contribute! The arrays must indeed be converted into strings. Traditionally option 1 was the only option for the MiniZinc driver, but since the latest release 2 would also be allowed.

This behaviour would be easy to add in the `MZNJSONEncoder` the idea would be that you would covert the custom type to the native Python data type that has the correct JSON representation.

I'm not fully convinced that this is supposed to go into the MiniZinc Python package though. This comes down to two reasons:
- Most importantly, it seems that allowing the assignment of NumPy arrays would hide a certain level of complexity. Since these arrays have to be converted to normal lists, I'm not sure if I wouldn't rather have people write `model[member] = list(my_np_array)` instead. This way it is actually visible for users that a transformation is happening and they can avoid doing this operation multiple times.
- Since there is currently no need, I don't want MiniZinc Python to have a dependency on NumPy (which is not always well supported on all platforms and architectures). I think there is probably a way around this, but it would be a bit more tricky to do the type checking without a (definitive) import.

I'm sure that the error at the moment seems like it comes out of nowhere so it would at least be a good idea to document that all objects that are assigned should be JSON serialisable and maybe check this during the assignment operation. This will at least trigger the error at the expected time.

**Comment by artsiomkaltovich** [comment]
Hello @Dekker1.

Thank you for your opinion, I agree that it is better not to hide the complex processing, so user won't be surprised by their model execution slowdown. But there is a problem with list(np.array) it works for 1d arrays only.

Yesterday I understood there is a better solution.
It is simple ``str(array).replace(" ", ", ")``. It should work fast enough because it is c-implemented function, rather then python code.
So I've tried to add such code to ``default`` method of json encoder, but because it is returned str, later json library thinks that it is a string at a whole, and argument is passed as string to minizinc, I've tried to find which method I can redefine to convert objects directly to json, there is ``encode`` method, but it is called with a dictionary ``dict(array_name=array)``, so the one should reimplement all basic conversions as well. :)

And then I found out there is a ``ndarray.tolist`` method. :)

And the most interesting, it is much faster then working with strings:

```
>>> a = np.array([[1, 2], [3, 4]])   
>>> timeit.timeit(lambda: str(a).replace(" ", ", "), number=10000)
0.42379060000007485  
>>> timeit.timeit(lambda: str(a.tolist()), number=10000)
0.008796500000002538  
```
So it is like 50 time faster, and it is pretty the same for python 3.6 and 3.8, but only for 2d, there is not such big difference for 1d, I guess it because of not optimized recursion or something like that. It was a long evening. :)

I would add numpy array support for serialization, because it can save time for user, none of us thought about ``tolist`` method :)

And we can avoid adding numpy as a dependency by something like

```
try:
    import numpy as np
except:
    class np:
        class ndarray:
            pass  # stub for isinstance check

```

But it is up to you :)

If you are interested I've created PR to my repository you can look at it before and if you want to add this code to python-minizinc I could create PR to this repo. :)
https://github.com/ArtyomKaltovich/minizinc-python/pull/1/files

>I'm sure that the error at the moment seems like it comes out of nowhere so it would at least be a good idea to document that all objects that are assigned should be JSON serialisable and maybe check this during the assignment operation. This will at least trigger the error at the expected time.

We can also catch all TypeError exception and suggest calling ``tolist`` if there is 'ndarray' in the call, or check it before call :)

Thank you and Happy New Year,
Artyom.

**Comment by Dekker1** [comment]
You are correct that it should be `model[member] = my_np_array.tolist()`. That seems to be the most efficient way to do the conversion.

I woud lean towards checking if the objects are JSON serialisable and throwing an error if this is not the case. Since the JSON serialiser doesn't seem to have a specific interface this would probably involve checking against all known serialisable types whenever you write the Model indexed objects. Not the greatest option, but it would work. (The other suggestion seems to be to catch the error when serialising, but that wouldn't be much different from how it is now.
