### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by dirkvbok** [MiniZinc/minizinc-python#47]
Hi,

I've come across two issues in the following code:
https://github.com/MiniZinc/minizinc-python/blob/953ea27cda801f6cac8635c0ff3d7b87a8df1e10/src/minizinc/result.py#L97-L107

#### Time format
The first one is that the following error occurs: `ValueError: could not convert string to float: '64.218 (1:04.218)'`. I believe that when the time is above a minute, this issue occurs. The time comes in as `64.218 (1:04.218)` and thus I think it should be rewritten something like this:

```   
 if tt is timedelta:
        time_us = int(float(value) * 1000000)
        stats[name] = timedelta(microseconds=time_us)
 elif (tt is None and ("time" in name or "Time" in name)):
        value = value.split(" ")[0]
        time_us = int(float(value) * 1000000)
        stats[name] = timedelta(microseconds=time_us)
```

#### Thousands separator
Also, there is an issue with the "thousands separator". When the number is large enough (in the thousands), it comes in like this: "24,895,209", which gives me the following error: `ValueError: invalid literal for int() with base 10: '24,895,209'`. So for my code to work I needed to change:
```
    elif tt is not None:
        stats[name] = tt(value)
```

to:

```
    elif tt is not None:
        if tt is int:
            stats[name] = int(float(value.replace(",", "")))
        else:
            stats[name] = tt(value)
```

I think it simply has to do with my system's time and number format, but I don't want to dive too deep into it. Just wanted to let you know that these issues exist. Otherwise very happy with the Python package of MiniZinc 👌

**Comment by Dekker1** [comment]
Sorry for the late response. I was on leave.

The regex parsing of statistics is maybe a little unstable, but does currently abide by the MiniZinc statistics standard: https://www.minizinc.org/doc-2.6.0/en/fzn-spec.html#statistics-output

The usage of real time output in parentheses, and thousand separators, would not be according to the standards.

At the moment the problem is likely that the specification is not very exact and that it is not tested by the MiniZinc executable itself. It might be a good idea to inform the solver implementer of the issue.

Likely I will better ensure that the statistics are gathered as strings when parsing is not possible.
