### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Pinzauti** [MiniZinc/minizinc-python#60]
Hi there. I'm trying to run the [basic example](https://minizinc-python.readthedocs.io/en/latest/getting_started.html#a-basic-example) on my system (Windows 11, Python 3.10, MiniZinc 2.6.3).

The files are named ```nqueens.mzn``` and ```example.py```. minizinc-python is installed through pip as required. MiniZinc is installed in the default path.

The following error is however returned:

```
minizinc.error.MiniZincError: MiniZinc stopped with a non-zero exit code, but did not output an error message.
```

Any solution? Thanks

**Comment by Pinzauti** [comment]
Fixed adding the installation folder to ```PATH```. Sorry for the useless issue.
However, my two cents:
- The error message was rather unclear.
- According to the [documentation](https://minizinc-python.readthedocs.io/en/latest/getting_started.html#installation) this should not be required if MiniZinc is installed in the default location (which I suppose is the one suggested by the installer, that I did not change).

**Comment by Dekker1** [comment]
Hi,

I agree that this is indeed not the best error message, but since we do use executables to run in the background, there are certain things that we cannot control.
I'm not sure what executable was actually run, but I would have assumed that you would have gotten the warning about incompatible MiniZinc versions beforehand.

We manually add the default MiniZinc installation locations to the end of the `PATH`, such that if users do not have to configure the system PATH for most simple cases. If you've made manual changes then a different version of MiniZinc might already be found.

What was is that the Python package found? And what is your MiniZinc installation location? Is it not one of the locations listed here: https://github.com/MiniZinc/minizinc-python/blob/develop/src/minizinc/driver.py#L32-L37 ?

**Comment by Pinzauti** [comment]
Yep, it is in the list, it is this one: ```C:\Program Files\MiniZinc```. 

As far as what the Python package found I have no idea, I installed the MiniZinc bundle some months ago and I did update it a couple of times (re-downloading the installer from the website). However I did not make any manual changes, and I supposed that new versions replaced the old ones.

I also tried installing the last version of MiniZinc (again, default location, no manual changes) in a fresh system (no previous installations) but the same error persisted.

**Comment by Dekker1** [comment]
There is mostly the question of if the executable that it finds isn't MiniZinc, what does it find instead. I would suggest that, in the same environment where you run your Python script, you run `which minizinc` or even just `minizinc` and see what it actually does. Because it seems likely that you have a different executable with the same name on your PATH
