### ISSUE TITLE
Driver is None

### ISSUE THREAD

**Issue by Greater-Gold** [MiniZinc/minizinc-python#72]
We are using Anaconda and created an env called MENuS. We are trying to follow the example in the documentation: https://minizinc-python.readthedocs.io/en/latest/getting_started.html#installation (Windows)

![photo_5157171050436471768_x](https://user-images.githubusercontent.com/71665963/219977033-9c11ddf2-3379-4315-a563-62055c62e631.jpg)

**Comment by Dekker1** [comment]
It sounds like you did not install MiniZinc itself on your computer, which is explicitly stated as a dependency on the top of that very same page in the documentation.

**Comment by Dekker1** [comment]
When loading MiniZinc Python you would even have received a warning to remind you of this fact.

**Comment by Greater-Gold** [comment]
Minizinc is already installed in the computer. Still, I wanted to have it installed only in the python env

**Comment by Dekker1** [comment]
If MiniZinc is installed, then this error means that either the MiniZinc executable cannot be found or the version of MiniZinc is not supported. The former happens when MiniZinc is not installed in a default location and `minizinc` is not available on the executable `$PATH`. MiniZinc Python requires at least MiniZinc version 2.5.0.

To manually initialise the driver, please have a look at: https://minizinc-python.readthedocs.io/en/latest/advanced_usage.html#using-multiple-minizinc-versions
